# Generated by Django 5.2.8 on 2026-09-03 11:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Subscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price_per_student', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name="Bir o'quvchidan olinadigan summa")),
                ('card_number', models.CharField(blank=True, default='', max_length=32, verbose_name="To'lov qabul qilinadigan karta raqami")),
                ('card_holder_name', models.CharField(blank=True, default='', max_length=64, verbose_name='Karta egasi (ixtiyoriy)')),
                ('payment_day', models.PositiveSmallIntegerField(default=15, verbose_name="Har oyning nechanchi kuni to'lov qilinishi kerak")),
                ('last_payment_date', models.DateField(blank=True, null=True)),
                ('next_due_date', models.DateField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Obuna sozlamalari',
                'verbose_name_plural': 'Obuna sozlamalari',
            },
        ),
        migrations.CreateModel(
            name='PaymentReceipt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('receipt_image', models.ImageField(upload_to='billing_receipts/%Y/%m/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('pending', 'Kutilmoqda'), ('approved', 'Tasdiqlangan'), ('rejected', 'Rad etilgan')], default='pending', max_length=10)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_receipts', to=settings.AUTH_USER_MODEL)),
                ('uploaded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='uploaded_receipts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': "To'lov cheki",
                'verbose_name_plural': "To'lov cheklari",
                'ordering': ['-uploaded_at'],
            },
        ),
    ]
