# Generated by Django 5.2.8 on 2026-09-05 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscription',
            name='billing_enabled',
            field=models.BooleanField(default=True, help_text="O'chirilsa - markaz platformani to'liq sotib olgan hisoblanadi, hech qachon bloklanmaydi.", verbose_name="Oylik to'lov tizimi yoqilganmi"),
        ),
    ]
