<<<<<<< HEAD
# Generated by Django 5.2.3 on 2025-11-03 13:17
=======
# Generated by Django 5.2.6 on 2025-10-16 19:11
>>>>>>> 82e4ca92702e200abb25ae916d02cb5601e1fa5f

import datetime
import django.contrib.auth.models
<<<<<<< HEAD
import django.contrib.auth.validators
=======
>>>>>>> 82e4ca92702e200abb25ae916d02cb5601e1fa5f
import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now_add=True, verbose_name='Updated at')),
                ('title', models.CharField(max_length=256, verbose_name='title')),
                ('description', models.TextField(blank=True, null=True, verbose_name='description')),
                ('duration', models.CharField(max_length=256, verbose_name='duration')),
                ('price', models.IntegerField(verbose_name='price')),
            ],
            options={
                'verbose_name': 'course',
                'verbose_name_plural': 'courses',
                'db_table': 'courses',
            },
        ),
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now_add=True, verbose_name='Updated at')),
                ('full_name', models.CharField(max_length=256, verbose_name='full name')),
                ('birth_date', models.DateField(verbose_name='birth date')),
                ('phone', models.CharField(max_length=256, verbose_name='phone')),
                ('address', models.CharField(max_length=256, verbose_name='address')),
                ('status', models.CharField(choices=[('Active', 'Active'), ('Archive', 'Archive')], max_length=256, verbose_name='status')),
            ],
            options={
                'verbose_name': 'teacher',
                'verbose_name_plural': 'teachers',
                'db_table': 'teachers',
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('role', models.CharField(blank=True, choices=[('manager', 'Manager'), ('teacher', 'Teacher'), ('reception', 'Reception'), ('accountant', 'Accountant')], max_length=20, null=True)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now_add=True, verbose_name='Updated at')),
                ('title', models.CharField(max_length=256, verbose_name='title')),
<<<<<<< HEAD
                ('lesson_days', models.CharField(choices=[('mo we fri', 'Mon Wed Fri'), ('tu thu sa', 'Tu Thu Sat')], max_length=256, verbose_name='lesson days')),
                ('time', models.CharField(max_length=30, verbose_name='time')),
                ('date_started', models.DateField()),
                ('status', models.CharField(choices=[('Active', 'Active'), ('Finished', 'Finished')], default='ACTIVE', max_length=256, verbose_name='status')),
                ('course', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='groups', to='common.course', verbose_name='course')),
                ('teacher', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='groups', to='common.teacher', verbose_name='teacher')),
=======
                ('lesson_days', models.CharField(choices=[('mo we fri', 'Mo We Fri'), ('tu thu sa', 'Tu Thu Sa')], max_length=256, verbose_name='lesson days')),
                ('date_started', models.DateField(verbose_name='date')),
                ('status', models.CharField(choices=[('active', 'ACTIVE'), ('finished', 'FINISHED'), ('archived', 'ARCHIVED')], default='ACTIVE', max_length=256, verbose_name='status')),
                ('course', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='groups', to='common.course', verbose_name='course')),
                ('teacher', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='groups', to='common.teacher', verbose_name='teacher')),
>>>>>>> 82e4ca92702e200abb25ae916d02cb5601e1fa5f
            ],
            options={
                'verbose_name': 'group',
                'verbose_name_plural': 'groups',
                'db_table': 'groups',
            },
        ),
        migrations.CreateModel(
            name='Lead',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now_add=True, verbose_name='Updated at')),
                ('full_name', models.CharField(max_length=256, verbose_name='full name')),
                ('birth_date', models.DateField(verbose_name='birth date')),
                ('phone', models.CharField(max_length=256, verbose_name='phone')),
                ('address', models.CharField(max_length=256, verbose_name='address')),
                ('status', models.CharField(choices=[('ACTIVE', 'ACTIVE'), ('TRIAL', 'TRIAL'), ('FROZEN', 'FROZEN')], max_length=256, verbose_name='status')),
                ('interested_course', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='leads', to='common.course', verbose_name='interested course')),
            ],
            options={
                'verbose_name': 'lead',
                'verbose_name_plural': 'leads',
                'db_table': 'leads',
            },
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now_add=True, verbose_name='Updated at')),
                ('full_name', models.CharField(max_length=256, verbose_name='full name')),
                ('birth_date', models.DateField(verbose_name='birth date')),
                ('phone', models.CharField(max_length=256, verbose_name='phone')),
                ('address', models.CharField(max_length=256, verbose_name='address')),
                ('balance', models.IntegerField(verbose_name='balance')),
<<<<<<< HEAD
                ('date_joined', models.DateField(blank=True, default=datetime.date.today, null=True, verbose_name='joined')),
                ('status', models.CharField(choices=[('Active', 'Active'), ('Archive', 'Archive')], max_length=256, verbose_name='status')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='students', to='common.group', verbose_name='group')),
=======
                ('date_joined', models.DateTimeField(verbose_name='date joined')),
                ('status', models.CharField(choices=[('active', 'ACTIVE'), ('frozen', 'frozen'), ('archived', 'ARCHIVED')], max_length=256, verbose_name='status')),
                ('group', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='students', to='common.group', verbose_name='group')),
>>>>>>> 82e4ca92702e200abb25ae916d02cb5601e1fa5f
            ],
            options={
                'verbose_name': 'student',
                'verbose_name_plural': 'students',
                'db_table': 'students',
            },
        ),
        migrations.CreateModel(
<<<<<<< HEAD
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.PositiveIntegerField(verbose_name='amount')),
                ('date', models.DateField(default=datetime.date.today, verbose_name='date')),
                ('group', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='payment', to='common.group')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='common.student')),
            ],
            options={
                'verbose_name': 'payment',
                'verbose_name_plural': 'payment',
                'db_table': 'payment',
            },
        ),
        migrations.CreateModel(
            name='Grade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_time', models.DateField()),
                ('grade', models.PositiveSmallIntegerField(default=0)),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='common.group')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='common.student')),
=======
            name='BaseUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('full_name', models.CharField(blank=True, max_length=256, null=True, verbose_name='full name')),
                ('username', models.CharField(max_length=256, unique=True, verbose_name='username')),
                ('phone', models.CharField(max_length=256, null=True, verbose_name='phone')),
                ('role', models.CharField(choices=[('manager', 'Manager'), ('reception', 'Reception'), ('accountant', 'Accountant'), ('teacher', 'teacher')], max_length=256, null=True, verbose_name='role')),
                ('password', models.CharField(max_length=256, verbose_name='password')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now_add=True)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
                ('teacher_profile', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='users', to='common.teacher', verbose_name='teacher profile')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'db_table': 'users',
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
>>>>>>> 82e4ca92702e200abb25ae916d02cb5601e1fa5f
            ],
        ),
        migrations.CreateModel(
            name='Attendance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_time', models.DateField()),
                ('is_present', models.BooleanField(default=False)),
                ('group', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='attendances', to='common.group')),
                ('student', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='attendances', to='common.student')),
            ],
            options={
                'ordering': ['-date_time'],
                'unique_together': {('student', 'date_time')},
            },
        ),
    ]
