# Generated by Django 5.2.6 on 2025-10-04 14:16

import django.contrib.auth.models
import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now_add=True, verbose_name='Updated at')),
                ('title', models.CharField(max_length=256, verbose_name='title')),
                ('description', models.TextField(blank=True, null=True, verbose_name='description')),
                ('duration', models.CharField(max_length=256, verbose_name='duration')),
                ('price', models.DecimalField(decimal_places=2, max_digits=16, verbose_name='price')),
            ],
            options={
                'verbose_name': 'course',
                'verbose_name_plural': 'courses',
                'db_table': 'courses',
            },
        ),
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now_add=True, verbose_name='Updated at')),
                ('full_name', models.CharField(max_length=256, verbose_name='full name')),
                ('birth_date', models.DateField(verbose_name='birth date')),
                ('phone', models.CharField(max_length=256, verbose_name='phone')),
                ('address', models.CharField(max_length=256, verbose_name='address')),
                ('status', models.CharField(choices=[('active', 'ACTIVE'), ('archived', 'ARCHIVED')], max_length=256, verbose_name='status')),
            ],
            options={
                'verbose_name': 'teacher',
                'verbose_name_plural': 'teachers',
                'db_table': 'teachers',
            },
        ),
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now_add=True, verbose_name='Updated at')),
                ('title', models.CharField(max_length=256, verbose_name='title')),
                ('lesson_days', models.CharField(choices=[('mo we fri', 'Mo We Fri'), ('tu thu sa', 'Tu Thu Sa')], max_length=256, verbose_name='lesson days')),
                ('time', models.TimeField(verbose_name='time')),
                ('date_started', models.DateField(auto_now_add=True)),
                ('status', models.CharField(choices=[('active', 'ACTIVE'), ('finished', 'FINISHED'), ('archived', 'ARCHIVED')], default='ACTIVE', max_length=256, verbose_name='status')),
                ('course', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='groups', to='common.course', verbose_name='course')),
                ('teacher', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='groups', to='common.teacher', verbose_name='teacher')),
            ],
            options={
                'verbose_name': 'group',
                'verbose_name_plural': 'groups',
                'db_table': 'groups',
            },
        ),
        migrations.CreateModel(
            name='Lead',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now_add=True, verbose_name='Updated at')),
                ('full_name', models.CharField(max_length=256, verbose_name='full name')),
                ('birth_date', models.DateField(verbose_name='birth date')),
                ('phone', models.CharField(max_length=256, verbose_name='phone')),
                ('address', models.CharField(max_length=256, verbose_name='address')),
                ('status', models.CharField(choices=[], max_length=256, verbose_name='status')),
                ('interested_course', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='leads', to='common.course', verbose_name='interested course')),
            ],
            options={
                'verbose_name': 'lead',
                'verbose_name_plural': 'leads',
                'db_table': 'leads',
            },
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now_add=True, verbose_name='Updated at')),
                ('full_name', models.CharField(max_length=256, verbose_name='full name')),
                ('birth_date', models.DateField(verbose_name='birth date')),
                ('phone', models.CharField(max_length=256, verbose_name='phone')),
                ('address', models.CharField(max_length=256, verbose_name='address')),
                ('balance', models.DecimalField(decimal_places=2, max_digits=16, verbose_name='balance')),
                ('date_joined', models.DateTimeField(verbose_name='date joined')),
                ('status', models.CharField(choices=[], max_length=256, verbose_name='status')),
                ('parent_profile', models.CharField(max_length=256, verbose_name='parent profile')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='students', to='common.group', verbose_name='group')),
            ],
            options={
                'verbose_name': 'student',
                'verbose_name_plural': 'students',
                'db_table': 'students',
            },
        ),
        migrations.CreateModel(
            name='Attendance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now_add=True, verbose_name='Updated at')),
                ('is_present', models.BooleanField(verbose_name='is present')),
                ('grade', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10)], verbose_name='grade')),
                ('date_time', models.DateTimeField(verbose_name='date time')),
                ('student_group', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='attendances', to='common.group', verbose_name='student group')),
                ('student', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='student', to='common.student', verbose_name='student')),
            ],
            options={
                'verbose_name': 'attendance',
                'verbose_name_plural': 'students',
                'db_table': 'attendances',
            },
        ),
        migrations.CreateModel(
            name='BaseUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('full_name', models.CharField(blank=True, max_length=256, null=True, verbose_name='full name')),
                ('username', models.CharField(max_length=256, unique=True, verbose_name='username')),
                ('phone', models.CharField(max_length=256, verbose_name='phone')),
                ('role', models.CharField(choices=[('manager', 'Manager'), ('reception', 'Reception'), ('accountant', 'Accountant'), ('teacher', 'Teacher')], max_length=256, verbose_name='role')),
                ('password', models.CharField(max_length=256, verbose_name='password')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now_add=True)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
                ('teacher_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='users', to='common.teacher', verbose_name='teacher profile')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'db_table': 'users',
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
    ]
