# Generated by Django 5.2.6 on 2025-11-02 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='parent_telegram_id',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
