# Generated by Django 5.2.3 on 2025-11-08 13:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Classroom',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=100, verbose_name='Name')),
                ('capacity', models.CharField(max_length=100, verbose_name='capacity')),
            ],
        ),
        migrations.CreateModel(
            name='RoomSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.CharField(max_length=100, verbose_name='time')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='common.group')),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='schedules', to='common.classroom')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='common.teacher')),
            ],
        ),
    ]
