# Generated by Django 5.2.6 on 2025-10-08 19:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='parent_profile',
        ),
        migrations.AlterField(
            model_name='baseuser',
            name='created_at',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='baseuser',
            name='updated_at',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='course',
            name='price',
            field=models.IntegerField(verbose_name='price'),
        ),
        migrations.AlterField(
            model_name='group',
            name='date_started',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='student',
            name='balance',
            field=models.IntegerField(verbose_name='balance'),
        ),
    ]
