# Generated by Django 5.2.6 on 2025-11-08 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='price',
        ),
        migrations.AddField(
            model_name='group',
            name='price',
            field=models.IntegerField(default=1, verbose_name='price'),
            preserve_default=False,
        ),
    ]
