# Generated by Django 5.2.6 on 2025-10-04 15:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='baseuser',
            name='phone',
            field=models.CharField(max_length=256, null=True, verbose_name='phone'),
        ),
        migrations.AlterField(
            model_name='baseuser',
            name='role',
            field=models.CharField(choices=[('manager', 'Manager'), ('reception', 'Reception'), ('accountant', 'Accountant'), ('teacher', 'Teacher')], max_length=256, null=True, verbose_name='role'),
        ),
        migrations.AlterField(
            model_name='baseuser',
            name='teacher_profile',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='users', to='common.teacher', verbose_name='teacher profile'),
        ),
    ]
