# Generated by Django 5.2.6 on 2025-11-02 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0002_student_parent_telegram_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='code',
            field=models.CharField(blank=True, max_length=8, null=True, unique=True),
        ),
    ]
