# Generated by Django 5.2.6 on 2025-10-04 15:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0002_alter_baseuser_phone_alter_baseuser_role_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='baseuser',
            name='teacher_profile',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='users', to='common.teacher', verbose_name='teacher profile'),
        ),
    ]
