# Generated by Django 5.2.6 on 2025-11-02 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0003_student_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='group',
            name='end_time',
            field=models.TimeField(blank=True, null=True, verbose_name='lesson end time'),
        ),
        migrations.AddField(
            model_name='group',
            name='start_time',
            field=models.TimeField(blank=True, null=True, verbose_name='lesson start time'),
        ),
    ]
