# Generated by Django 5.2.6 on 2025-11-08 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0003_group_room_alter_group_course_alter_group_teacher_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='classroom',
            name='Name',
        ),
        migrations.DeleteModel(
            name='RoomSchedule',
        ),
        migrations.AddField(
            model_name='classroom',
            name='name',
            field=models.CharField(default=1, max_length=100, verbose_name='name'),
            preserve_default=False,
        ),
    ]
