# Generated by Django 5.2.3 on 2025-11-09 03:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0004_remove_classroom_name_delete_roomschedule_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='group',
            name='time',
        ),
        migrations.AddField(
            model_name='group',
            name='end_time',
            field=models.CharField(default=1, max_length=30, verbose_name='end_time'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='group',
            name='start_time',
            field=models.CharField(default=1, max_length=30, verbose_name='start_time'),
            preserve_default=False,
        ),
    ]
