# Generated by Django 5.2.6 on 2025-11-02 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0004_group_end_time_group_start_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='group',
            name='lesson_days',
            field=models.CharField(choices=[('mo we fri', 'Mo We Fri'), ('tu thu sa sun', 'Tu Thu Sa Sun')], max_length=256, verbose_name='lesson days'),
        ),
    ]
