# Generated by Django 5.2.6 on 2025-11-02 17:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0005_alter_group_lesson_days'),
    ]

    operations = [
        migrations.AlterField(
            model_name='group',
            name='lesson_days',
            field=models.CharField(choices=[('mo we fri', 'Mo We Fri'), ('tu thu sa', 'Tu Thu Sa')], max_length=256, verbose_name='lesson days'),
        ),
    ]
