# Generated by Django 5.2.6 on 2025-11-03 03:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0006_alter_group_lesson_days'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='group',
            name='end_time',
        ),
        migrations.RemoveField(
            model_name='group',
            name='start_time',
        ),
        migrations.RemoveField(
            model_name='student',
            name='code',
        ),
        migrations.RemoveField(
            model_name='student',
            name='parent_telegram_id',
        ),
    ]
