# Generated by Django 5.2.8 on 2025-11-10 12:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0006_alter_payment_options_alter_payment_group'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='group',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='students', to='common.group', verbose_name='group'),
            preserve_default=False,
        ),
    ]
