# Generated by Django 5.2.8 on 2025-11-11 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0007_alter_student_group'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='debt',
            field=models.PositiveIntegerField(default=0, verbose_name='debt'),
        ),
    ]
