# Generated by Django 5.2.8 on 2025-11-11 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0008_payment_debt'),
    ]

    operations = [
        migrations.AlterField(
            model_name='group',
            name='end_time',
            field=models.TimeField(verbose_name='end_time'),
        ),
        migrations.AlterField(
            model_name='group',
            name='start_time',
            field=models.TimeField(verbose_name='start_time'),
        ),
    ]
