# Generated by Django 5.2.8 on 2025-11-11 13:45

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0009_alter_group_end_time_alter_group_start_time'),
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now_add=True, verbose_name='Updated at')),
                ('full_name', models.CharField(max_length=256, verbose_name='full name')),
                ('birth_date', models.DateField(blank=True, null=True, verbose_name='birth date')),
                ('phone', models.CharField(max_length=256, verbose_name='phone')),
                ('date_joined', models.DateField(blank=True, default=datetime.date.today, null=True, verbose_name='joined')),
                ('salary', models.PositiveIntegerField(verbose_name='Monthly Salary')),
                ('role', models.CharField(choices=[('administrator', 'Administrator'), ('accountant', 'Accountant'), ('support', 'Support'), ('receptionist', 'Receptionist')], max_length=256, verbose_name='status')),
            ],
            options={
                'verbose_name': 'Employee',
                'verbose_name_plural': 'Employee',
                'db_table': 'Employee',
            },
        ),
    ]
