# Generated by Django 5.2.8 on 2025-11-15 09:46

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0010_employee'),
    ]

    operations = [
        migrations.CreateModel(
            name='Wages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('administrator', 'Administrator'), ('accountant', 'Accountant'), ('support', 'Support'), ('receptionist', 'Receptionist')], max_length=256)),
                ('amount', models.PositiveIntegerField()),
                ('date', models.DateField(default=datetime.date.today)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='common.employee')),
            ],
        ),
    ]
