# Generated by Django 5.2.8 on 2025-11-15 09:58

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0011_wages'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wages',
            name='date',
            field=models.DateField(blank=True, default=datetime.date.today, null=True, verbose_name='date'),
        ),
    ]
