# Generated by Django 5.2.8 on 2026-08-31 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0014_course_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='informations',
            name='name',
            field=models.CharField(default=1, max_length=255, verbose_name='Name'),
            preserve_default=False,
        ),
    ]
