# Generated by Django 5.2.8 on 2026-09-02 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0015_informations_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='status',
            field=models.CharField(choices=[('Active', 'Active'), ('Archive', 'Archive')], default='Active', max_length=256, verbose_name='status'),
        ),
    ]
