# Generated by Django 5.2.8 on 2026-09-30 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0016_alter_student_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teacher',
            name='salary',
            field=models.CharField(help_text="Foiz: '20%', Fix summa (guruh uchun): '500000', Fix summa (o'quvchi boshiga): '200000'", max_length=100, verbose_name='salary'),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='type',
            field=models.CharField(choices=[('Precent', 'Precent'), ('Group by', 'Group by'), ('Student by', 'Student by')], max_length=100, verbose_name='type'),
        ),
    ]
