"""
Django settings for core project.

Generated by 'django-admin startproject' using Django 5.2.6.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""
import os
from pathlib import Path

import dj_database_url
from decouple import config

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
# ============================================================
# O'ZGARDI: SECRET_KEY endi kodda ochiq yozilmaydi, environment
# o'zgaruvchidan olinadi. Railway'da "Variables" bo'limiga
# SECRET_KEY qo'shishni unutmang. Agar u yerda topilmasa, xato
# bermasligi uchun default sifatida eski (lokal) kalit qoldirildi -
# lekin production'da albatta Railway'da yangisini kiriting.
# ============================================================
SECRET_KEY = config(
    'SECRET_KEY',
    default='django-insecure-^x)-ywaa^*_m!j&$(!gx$8yiiw2h76&qa(nfur+yy8fwmplv%@'
)

# SECURITY WARNING: don't run with debug turned on in production!
# ============================================================
# O'ZGARDI: Railway'da DEBUG=False qo'yiladi (Variables bo'limida).
# Agar hech narsa qo'yilmasa, lokalda ishlashda True bo'lib qoladi
# (default=True) - shuning uchun kompyuteringizda hech narsa
# buzilmaydi, faqat Railway'da DEBUG=False deb yozishni unutmang.
# ============================================================
DEBUG = config('DEBUG', default=True, cast=bool)




# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'django.contrib.humanize', 
    'django.forms',
    'rest_framework',
    'drf_yasg',
    "debug_toolbar",
    'common',
    'manager',
    'accountant',
    'reception',
    'teacher',
    'billing',

]

INTERNAL_IPS = [
    "127.0.0.1",
]

MIDDLEWARE = [
    "querycount.middleware.QueryCountMiddleware",
    "debug_toolbar.middleware.DebugToolbarMiddleware",  
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.locale.LocaleMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'billing.middleware.SubscriptionGateMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',

]

ROOT_URLCONF = 'core.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [os.path.join(BASE_DIR, 'templates')],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',

                'common.context_processors.center_info',
            ],
        },
    },
]

WSGI_APPLICATION = 'core.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

# ============================================================
# O'ZGARDI: ALLOWED_HOSTS endi environment o'zgaruvchidan
# vergul bilan ajratilgan holda o'qiladi. Agar Railway'da
# ALLOWED_HOSTS o'rnatilmasa, default sifatida '*' qoladi -
# ya'ni HECH NARSA BUZILMAYDI, faqat xavfsizlik uchun Railway'da
# aniq domeningizni yozib qo'yish tavsiya etiladi.
# ============================================================
ALLOWED_HOSTS = config('ALLOWED_HOSTS', default='*').split(',')

# ============================================================
# YANGI: CSRF_TRUSTED_ORIGINS - Railway (va boshqa https orqali
# ishlaydigan) domenlar uchun forma yuborishda "CSRF verification
# failed" xatosining oldini oladi. Lokalda kerak emas, shuning
# uchun default bo'sh.
# ============================================================
CSRF_TRUSTED_ORIGINS = [
    "https://*.up.railway.app"
]


BASE_DIR = Path(__file__).resolve().parent.parent

# ============================================================
# O'ZGARDI: DATABASES endi DATABASE_URL environment
# o'zgaruvchisi orqali PostgreSQL'ga ulanadi (Railway PostgreSQL
# qo'shganda buni avtomatik beradi). Agar DATABASE_URL topilmasa
# (masalan lokal kompyuteringizda), avvalgidek SQLite ishlataveradi -
# demak lokal ishlashingiz HECH NARSA O'ZGARMAYDI.
# ============================================================
DATABASE_URL = config('DATABASE_URL', default='')

if DATABASE_URL:
    DATABASES = {
        'default': dj_database_url.parse(DATABASE_URL, conn_max_age=600)
    }
else:
    DATABASES = {
        'default': {
            'ENGINE': 'django.db.backends.sqlite3',
            'NAME': BASE_DIR / 'db.sqlite3',
        }
    }



FORM_RENDERER = "django.forms.renderers.TemplatesSetting"

# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

# AUTH_PASSWORD_VALIDATORS = [
#     {
#         'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
#     },
#     {
#         'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
#     },
#     {
#         'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
#     },
#     {
#         'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
#     },
# ]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True

# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = "/static/"
STATIC_ROOT = BASE_DIR / "static/"
STATICFILES_DIRS = [BASE_DIR / "staticfiles"]

# ============================================================
# YANGI: WhiteNoise orqali statik fayllarni siqib (compress)
# va keshlab beradigan rejim - Railway'da CSS/JS/rasm fayllar
# to'g'ri va tez yuklanishi uchun kerak. MIDDLEWARE'da
# WhiteNoiseMiddleware sizda allaqachon bor edi, shu bilan birga
# ishlaydi.
# ============================================================
STATICFILES_STORAGE = 'whitenoise.storage.CompressedManifestStaticFilesStorage'

MEDIA_URL = "/media/"

MEDIA_ROOT = BASE_DIR / "mediafiles"


AUTH_USER_MODEL = "common.BaseUser"
# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

LOGIN_URL = "/sign-in/"

# Til sozlamalari
LANGUAGE_CODE = 'uz'  # Default til

LANGUAGES = [
    ('uz', 'O\'zbekcha'),
    ('en', 'English'),
    ('ru', 'Русский'),
]

USE_I18N = True
USE_L10N = True

# Tarjima fayllar uchun papka
import os
LOCALE_PATHS = [
    os.path.join(BASE_DIR, 'locale'),
]