# Generated by Django 5.2.8 on 2026-09-20 10:53

import django.core.validators
import django.db.models.deletion
import telegram_bot.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('common', '0016_alter_student_status'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BotUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('telegram_id', models.BigIntegerField(unique=True)),
                ('language', models.CharField(blank=True, choices=[('uz', "O'zbekcha"), ('ru', 'Русский'), ('en', 'English')], default='', max_length=2)),
                ('full_name', models.CharField(blank=True, max_length=255)),
                ('phone', models.CharField(blank=True, max_length=20)),
                ('is_manager', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'bot_users',
            },
        ),
        migrations.CreateModel(
            name='ManagerInvite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.CharField(default=telegram_bot.models._new_token, max_length=64, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField(default=telegram_bot.models._default_expiry)),
                ('used_at', models.DateTimeField(blank=True, null=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('used_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='telegram_bot.botuser')),
            ],
            options={
                'db_table': 'bot_manager_invites',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='TeacherRating',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('voter_hash', models.CharField(db_index=True, max_length=64)),
                ('stars', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('month', models.DateField(help_text='Oyning 1-sanasi')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ratings', to='common.group')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ratings', to='common.teacher')),
            ],
            options={
                'db_table': 'teacher_ratings',
                'constraints': [models.UniqueConstraint(fields=('voter_hash', 'group', 'teacher', 'month'), name='one_rating_per_voter_group_teacher_month'), models.CheckConstraint(condition=models.Q(('stars__gte', 1), ('stars__lte', 5)), name='rating_stars_1_to_5')],
            },
        ),
    ]
